# Curated node list for the backfill. One row per node:
#   (id, lab, name, product_line, epoch_name, eci_name, extra)
# epoch_name: row in all_ai_models.csv (dates, link, params, accessibility)
# eci_name:   row in eci_scores.csv — the launch snapshot where several exist
# extra:      dict of overrides (org, family, notes, ...)

M = []
def m(id, lab, name, pl, ep=None, eci=None, **extra):
    M.append(dict(id=id, lab=lab, name=name, product_line=pl, epoch=ep, eci=eci, **extra))

# ── OpenAI ─────────────────────────────────────────────────────────────────
L = 'openai'
m('gpt-1', L, 'GPT-1', 'gpt', 'GPT-1', family='gpt-1')
m('gpt-2', L, 'GPT-2', 'gpt', 'GPT-2 (1.5B)', family='gpt-2')
m('gpt-3', L, 'GPT-3', 'gpt', 'GPT-3 175B (davinci)', family='gpt-3')
m('codex', L, 'Codex', 'codex', 'Codex', family='gpt-3')
m('instructgpt', L, 'InstructGPT', 'gpt-3-5', 'InstructGPT 175B', family='gpt-3')
m('text-davinci-002', L, 'GPT-3.5 (text-davinci-002)', 'gpt-3-5', 'GPT-3.5 (davinci-002)', family='gpt-3-5')
m('text-davinci-003', L, 'GPT-3.5 (text-davinci-003)', 'gpt-3-5', 'GPT-3.5 (davinci-003)', family='gpt-3-5')
m('chatgpt', L, 'ChatGPT', 'gpt-3-5', None, family='gpt-3-5')
m('gpt-3-5-turbo', L, 'GPT-3.5 Turbo', 'gpt-3-5', 'GPT-3.5 Turbo', 'GPT-3.5 Turbo (Jun 2023)', family='gpt-3-5')
m('gpt-4', L, 'GPT-4', 'gpt', 'GPT-4 (Mar 2023)', 'GPT-4 (Mar 2023)', family='gpt-4')
m('gpt-4-turbo', L, 'GPT-4 Turbo', 'gpt', 'GPT-4 Turbo (Nov 2023)', 'GPT-4 Turbo (Nov 2023)', family='gpt-4')
m('gpt-4o', L, 'GPT-4o', 'gpt', 'GPT-4o', 'GPT-4o (May 2024)', family='gpt-4o')
m('gpt-4o-mini', L, 'GPT-4o mini', 'gpt-mini', 'GPT-4o mini', 'GPT-4o mini', family='gpt-4o')
m('o1-preview', L, 'o1-preview', 'o', 'o1-preview', 'o1-preview', family='o1')
m('o1-mini', L, 'o1-mini', 'o-mini', 'o1-mini', 'o1-mini', family='o1')
m('o1', L, 'o1', 'o', 'o1', 'o1', family='o1')
m('o3-mini', L, 'o3-mini', 'o-mini', 'o3-mini', 'o3-mini', family='o3')
m('gpt-4-5', L, 'GPT-4.5', 'gpt', 'GPT-4.5', 'GPT-4.5', family='gpt-4-5')
m('gpt-4-1', L, 'GPT-4.1', 'gpt', 'GPT-4.1', 'GPT-4.1', family='gpt-4-1')
m('gpt-4-1-mini', L, 'GPT-4.1 mini', 'gpt-mini', 'GPT-4.1 mini', 'GPT-4.1 mini', family='gpt-4-1')
m('gpt-4-1-nano', L, 'GPT-4.1 nano', 'gpt-nano', 'GPT-4.1 nano', 'GPT-4.1 nano', family='gpt-4-1')
m('o3', L, 'o3', 'o', 'o3', 'o3', family='o3')
m('o4-mini', L, 'o4-mini', 'o-mini', 'o4-mini', 'o4-mini', family='o4')
m('gpt-oss-120b', L, 'gpt-oss-120b', 'gpt-oss', 'gpt-oss-120b', 'gpt-oss-120b', family='gpt-oss')
m('gpt-oss-20b', L, 'gpt-oss-20b', 'gpt-oss', 'gpt-oss-20b', 'gpt-oss-20b', family='gpt-oss')
m('gpt-5', L, 'GPT-5', 'gpt', 'GPT-5', 'GPT-5', family='gpt-5')
m('gpt-5-mini', L, 'GPT-5 mini', 'gpt-mini', 'GPT-5 mini', 'GPT-5 mini', family='gpt-5')
m('gpt-5-nano', L, 'GPT-5 nano', 'gpt-nano', 'GPT-5 nano', 'GPT-5 nano', family='gpt-5')
m('gpt-5-codex', L, 'GPT-5-Codex', 'codex', 'GPT-5-Codex', None, family='gpt-5')
m('gpt-5-1', L, 'GPT-5.1', 'gpt', 'GPT-5.1', 'GPT-5.1', family='gpt-5')
m('gpt-5-2', L, 'GPT-5.2', 'gpt', None, 'GPT-5.2', family='gpt-5')
m('gpt-5-3-codex', L, 'GPT-5.3-Codex', 'codex', 'GPT-5.3 Codex', 'GPT-5.3 Codex', family='gpt-5')
m('gpt-5-4', L, 'GPT-5.4', 'gpt', 'GPT-5.4', 'GPT-5.4', family='gpt-5')
m('gpt-5-4-mini', L, 'GPT-5.4 mini', 'gpt-mini', 'GPT-5.4 Mini', 'GPT-5.4 Mini', family='gpt-5')
m('gpt-5-4-nano', L, 'GPT-5.4 nano', 'gpt-nano', 'GPT-5.4 Nano', 'GPT-5.4 Nano', family='gpt-5')
m('gpt-5-5', L, 'GPT-5.5', 'gpt', 'GPT-5.5', 'GPT-5.5', family='gpt-5')
m('gpt-5-6-sol', L, 'GPT-5.6 Sol', 'gpt', 'GPT-5.6 Sol', 'GPT-5.6 Sol', family='gpt-5-6')
m('gpt-5-6-terra', L, 'GPT-5.6 Terra', 'gpt-mini', 'GPT-5.6 Terra', 'GPT-5.6 Terra', family='gpt-5-6')
m('gpt-5-6-luna', L, 'GPT-5.6 Luna', 'gpt-nano', 'GPT-5.6 Luna', 'GPT-5.6 Luna', family='gpt-5-6')
m('gpt-6-astra', L, 'GPT-6 Astra', 'gpt-astra', 'GPT-6 Astra', 'GPT-6 Astra', family='gpt-6')
m('gpt-6-sol', L, 'GPT-6 Sol', 'gpt', 'GPT-6 Sol', None, family='gpt-6')
m('gpt-6-luna', L, 'GPT-6 Luna', 'gpt-nano', 'GPT-6 Luna', None, family='gpt-6')
m('gpt-6-1-sol', L, 'GPT-6.1 Sol', 'gpt', 'GPT-6.1 Sol', None, family='gpt-6')

# ── Anthropic ──────────────────────────────────────────────────────────────
L = 'anthropic'
m('claude-1', L, 'Claude', 'claude', 'Claude', None, family='claude-1')
m('claude-instant', L, 'Claude Instant', 'haiku', 'Claude Instant', 'Claude Instant', family='claude-1')
m('claude-2', L, 'Claude 2', 'claude', 'Claude 2', 'Claude 2', family='claude-2')
m('claude-2-1', L, 'Claude 2.1', 'claude', 'Claude 2.1', 'Claude 2.1', family='claude-2')
m('claude-3-haiku', L, 'Claude 3 Haiku', 'haiku', 'Claude 3 Haiku', 'Claude 3 Haiku', family='claude-3')
m('claude-3-sonnet', L, 'Claude 3 Sonnet', 'sonnet', 'Claude 3 Sonnet', 'Claude 3 Sonnet', family='claude-3')
m('claude-3-opus', L, 'Claude 3 Opus', 'opus', 'Claude 3 Opus', 'Claude 3 Opus', family='claude-3')
m('claude-3-5-sonnet-20240620', L, 'Claude 3.5 Sonnet', 'sonnet', 'Claude 3.5 Sonnet', 'Claude 3.5 Sonnet', family='claude-3-5')
m('claude-3-5-haiku', L, 'Claude 3.5 Haiku', 'haiku', 'Claude 3.5 Haiku', 'Claude 3.5 Haiku', family='claude-3-5')
m('claude-3-5-sonnet-20241022', L, 'Claude 3.5 Sonnet (Oct 2024)', 'sonnet', None, 'Claude 3.5 Sonnet (October 2024)', family='claude-3-5')
m('claude-3-7-sonnet', L, 'Claude 3.7 Sonnet', 'sonnet', 'Claude 3.7 Sonnet', 'Claude 3.7 Sonnet', family='claude-3-7')
m('claude-opus-4', L, 'Claude Opus 4', 'opus', 'Claude Opus 4', 'Claude Opus 4', family='claude-4')
m('claude-sonnet-4', L, 'Claude Sonnet 4', 'sonnet', 'Claude Sonnet 4', 'Claude Sonnet 4', family='claude-4')
m('claude-opus-4-1', L, 'Claude Opus 4.1', 'opus', 'Claude Opus 4.1', 'Claude Opus 4.1', family='claude-4')
m('claude-sonnet-4-5', L, 'Claude Sonnet 4.5', 'sonnet', 'Claude Sonnet 4.5', 'Claude Sonnet 4.5', family='claude-4-5')
m('claude-haiku-4-5', L, 'Claude Haiku 4.5', 'haiku', 'Claude Haiku 4.5', 'Claude Haiku 4.5', family='claude-4-5')
m('claude-opus-4-5', L, 'Claude Opus 4.5', 'opus', 'Claude Opus 4.5', 'Claude Opus 4.5', family='claude-4-5')
m('claude-opus-4-6', L, 'Claude Opus 4.6', 'opus', 'Claude Opus 4.6', 'Claude Opus 4.6', family='claude-4-6')
m('claude-sonnet-4-6', L, 'Claude Sonnet 4.6', 'sonnet', 'Claude Sonnet 4.6', 'Claude Sonnet 4.6', family='claude-4-6')
m('claude-mythos-preview', L, 'Claude Mythos Preview', 'mythos', 'Claude Mythos Preview', None, family='claude-mythos')
m('claude-opus-4-7', L, 'Claude Opus 4.7', 'opus', 'Claude Opus 4.7', 'Claude Opus 4.7', family='claude-4-7')
m('claude-opus-4-8', L, 'Claude Opus 4.8', 'opus', 'Claude Opus 4.8', 'Claude Opus 4.8', family='claude-4-8')
m('claude-fable-5', L, 'Claude Fable 5', 'fable', 'Claude Fable 5', 'Claude Fable 5', family='claude-5')
m('claude-mythos-5', L, 'Claude Mythos 5', 'mythos', 'Claude Mythos 5', None, family='claude-5')
m('claude-sonnet-5', L, 'Claude Sonnet 5', 'sonnet', 'Claude Sonnet 5', 'Claude Sonnet 5', family='claude-5')
m('claude-opus-5', L, 'Claude Opus 5', 'opus', 'Claude Opus 5', 'Claude Opus 5', family='claude-5')
m('claude-fable-5-1', L, 'Claude Fable 5.1', 'fable', 'Claude Fable 5.1', 'Claude Fable 5.1', family='claude-5')
m('claude-mythos-5-1', L, 'Claude Mythos 5.1', 'mythos', None, None, family='claude-5')
m('claude-opus-5-5', L, 'Claude Opus 5.5', 'opus', 'Claude Opus 5.5', 'Claude Opus 5.5', family='claude-5-5')
m('claude-sonnet-5-5', L, 'Claude Sonnet 5.5', 'sonnet', 'Claude Sonnet 5.5', 'Claude Sonnet 5.5', family='claude-5-5')

# ── Google / DeepMind ──────────────────────────────────────────────────────
L = 'google'
m('bert', L, 'BERT', 'bert', 'BERT-Large', org='Google AI Language')
m('t5', L, 'T5', 't5', 'T5-11B', org='Google Research')
m('meena', L, 'Meena', 'lamda', 'Meena', org='Google Brain')
m('switch-transformer', L, 'Switch Transformer', 't5', 'Switch', org='Google Brain')
m('gopher', L, 'Gopher', 'deepmind-lm', 'Gopher (280B)', org='DeepMind')
m('lamda', L, 'LaMDA', 'lamda', 'LaMDA', org='Google Brain')
m('chinchilla', L, 'Chinchilla', 'deepmind-lm', 'Chinchilla', org='DeepMind')
m('palm', L, 'PaLM', 'palm', 'PaLM (540B)', org='Google Research')
m('flan-t5', L, 'Flan-T5', 't5', 'Flan-T5 11B', org='Google Research')
m('flan-palm', L, 'Flan-PaLM', 'palm', 'Flan-PaLM 540B', org='Google Research')
m('palm-2', L, 'PaLM 2', 'palm', 'PaLM 2', 'PaLM 2-L')
m('gemini-1-0-ultra', L, 'Gemini 1.0 Ultra', 'gemini-ultra', 'Gemini 1.0 Ultra', None, family='gemini-1')
m('gemini-1-0-pro', L, 'Gemini 1.0 Pro', 'gemini-pro', 'Gemini 1.0 Pro', 'Gemini 1.0 Pro', family='gemini-1')
m('gemma', L, 'Gemma', 'gemma', 'Gemma 7B', 'Gemma 7B', family='gemma')
m('gemini-1-5-pro', L, 'Gemini 1.5 Pro', 'gemini-pro', 'Gemini 1.5 Pro', 'Gemini 1.5 Pro (May 2024)', family='gemini-1-5')
m('gemini-1-5-flash', L, 'Gemini 1.5 Flash', 'gemini-flash', 'Gemini 1.5 Flash', 'Gemini 1.5 Flash (May 2024)', family='gemini-1-5')
m('gemma-2', L, 'Gemma 2', 'gemma', 'Gemma 2 27B', 'Gemma 2 27B', family='gemma')
m('gemini-2-0-flash', L, 'Gemini 2.0 Flash', 'gemini-flash', 'Gemini 2.0 Flash', 'Gemini 2.0 Flash (Dec 2024)', family='gemini-2')
m('gemini-2-0-pro', L, 'Gemini 2.0 Pro', 'gemini-pro', 'Gemini 2.0 Pro', 'Gemini 2.0 Pro', family='gemini-2')
m('gemini-2-0-flash-lite', L, 'Gemini 2.0 Flash-Lite', 'gemini-flash-lite', 'Gemini 2.0 Flash-Lite', None, family='gemini-2')
m('gemma-3', L, 'Gemma 3', 'gemma', 'Gemma 3 27B', 'Gemma 3 27B', family='gemma')
m('gemini-2-5-pro', L, 'Gemini 2.5 Pro', 'gemini-pro', 'Gemini 2.5 Pro (Mar 2025)', 'Gemini 2.5 Pro (Mar 2025)', family='gemini-2-5')
m('gemini-2-5-flash', L, 'Gemini 2.5 Flash', 'gemini-flash', 'Gemini 2.5 Flash', 'Gemini 2.5 Flash (Apr 2025)', family='gemini-2-5')
m('gemini-2-5-flash-lite', L, 'Gemini 2.5 Flash-Lite', 'gemini-flash-lite', 'Gemini 2.5 Flash-Lite', 'Gemini 2.5 Flash-Lite (Jun 2025)', family='gemini-2-5')
m('gemini-3-pro', L, 'Gemini 3 Pro', 'gemini-pro', 'Gemini 3 Pro', 'Gemini 3 Pro', family='gemini-3')
m('gemini-3-flash', L, 'Gemini 3 Flash', 'gemini-flash', 'Gemini 3 Flash', 'Gemini 3 Flash', family='gemini-3')
m('gemini-3-1-pro', L, 'Gemini 3.1 Pro', 'gemini-pro', 'Gemini 3.1 Pro', 'Gemini 3.1 Pro', family='gemini-3')
m('gemini-3-1-flash-lite', L, 'Gemini 3.1 Flash-Lite', 'gemini-flash-lite', 'Gemini 3.1 Flash-Lite', 'Gemini 3.1 Flash-Lite', family='gemini-3')
m('gemma-4', L, 'Gemma 4', 'gemma', 'Gemma 4 31B IT', 'Gemma 4 31B IT', family='gemma')
m('gemini-3-5-flash', L, 'Gemini 3.5 Flash', 'gemini-flash', 'Gemini 3.5 Flash', 'Gemini 3.5 Flash', family='gemini-3-5')
m('gemini-3-5-pro', L, 'Gemini 3.5 Pro', 'gemini-pro', None, None, family='gemini-3-5')
m('gemini-3-5-flash-lite', L, 'Gemini 3.5 Flash-Lite', 'gemini-flash-lite', 'Gemini 3.5 Flash-Lite', 'Gemini 3.5 Flash-Lite', family='gemini-3-5')
m('gemini-3-6-flash', L, 'Gemini 3.6 Flash', 'gemini-flash', 'Gemini 3.6 Flash', 'Gemini 3.6 Flash', family='gemini-3-5')
m('gemini-3-7-flash', L, 'Gemini 3.7 Flash', 'gemini-flash', 'Gemini 3.7 Flash', 'Gemini 3.7 Flash', family='gemini-3-5')
m('gemini-3-8-flash', L, 'Gemini 3.8 Flash', 'gemini-flash', 'Gemini 3.8 Flash', 'Gemini 3.8 Flash', family='gemini-3-5')
m('gemini-4-argon', L, 'Gemini 4 Argon', 'gemini-pro', 'Gemini 4 Argon', None, family='gemini-4')

# ── Meta ───────────────────────────────────────────────────────────────────
L = 'meta'
m('roberta', L, 'RoBERTa', 'roberta', 'RoBERTa Large', org='Facebook AI')
m('opt-175b', L, 'OPT-175B', 'opt', 'OPT-175B')
m('galactica', L, 'Galactica', 'opt', 'Galactica')
m('llama', L, 'LLaMA', 'llama', 'LLaMA-65B', 'LLaMA-65B', family='llama-1')
m('llama-2', L, 'Llama 2', 'llama', 'Llama 2-70B', 'Llama 2-70B', family='llama-2')
m('code-llama', L, 'Code Llama', 'code-llama', 'Code Llama-34B', None, family='llama-2')
m('llama-3', L, 'Llama 3', 'llama', 'Llama 3-70B', 'Llama 3-70B', family='llama-3')
m('llama-3-1-405b', L, 'Llama 3.1 405B', 'llama', 'Llama 3.1-405B', 'Llama 3.1-405B', family='llama-3')
m('llama-3-1-70b', L, 'Llama 3.1 70B', 'llama-mid', 'Llama 3.1-70B', 'Llama 3.1-70B', family='llama-3')
m('llama-3-1-8b', L, 'Llama 3.1 8B', 'llama-small', 'Llama 3.1-8B', 'Llama 3.1-8B', family='llama-3')
m('llama-3-3-70b', L, 'Llama 3.3 70B', 'llama-mid', 'Llama 3.3 70B', 'Llama 3.3 70B', family='llama-3')
m('llama-4-scout', L, 'Llama 4 Scout', 'llama-small', 'Llama 4 Scout', 'Llama 4 Scout', family='llama-4')
m('llama-4-maverick', L, 'Llama 4 Maverick', 'llama-mid', 'Llama 4 Maverick', 'Llama 4 Maverick', family='llama-4')
m('llama-4-behemoth', L, 'Llama 4 Behemoth', 'llama', 'Llama 4 Behemoth (preview)', None, family='llama-4')
m('muse-spark', L, 'Muse Spark', 'muse', 'Muse Spark', 'Muse Spark', family='muse')
m('muse-spark-1-1', L, 'Muse Spark 1.1', 'muse', 'Muse Spark 1.1', 'Muse Spark 1.1', family='muse')
m('muse-spark-1-2', L, 'Muse Spark 1.2', 'muse', 'Muse Spark 1.2', 'Muse Spark 1.2', family='muse')
m('muse-spark-1-3', L, 'Muse Spark 1.3', 'muse', 'Muse Spark 1.3', 'Muse Spark 1.3', family='muse')
m('muse-glimmer', L, 'Muse Glimmer', 'muse-open', 'Muse Glimmer', None, family='muse')

# ── DeepSeek ───────────────────────────────────────────────────────────────
L = 'deepseek'
m('deepseek-coder', L, 'DeepSeek Coder', 'deepseek-coder', 'DeepSeek Coder 33B', 'DeepSeek Coder 33B', family='deepseek-coder')
m('deepseek-llm', L, 'DeepSeek LLM', 'deepseek', 'DeepSeek LLM 67B', 'DeepSeek LLM 67B', family='deepseek-llm')
m('deepseek-v2', L, 'DeepSeek V2', 'deepseek', 'DeepSeek-V2 (MoE-236B)', 'DeepSeek-V2 (MoE-236B, May 2024)', family='deepseek-v2')
m('deepseek-coder-v2', L, 'DeepSeek Coder V2', 'deepseek-coder', 'DeepSeek-Coder-V2 236B', None, family='deepseek-v2')
m('deepseek-v2-5', L, 'DeepSeek V2.5', 'deepseek', 'DeepSeek-V2.5', None, family='deepseek-v2')
m('deepseek-v3', L, 'DeepSeek V3', 'deepseek', 'DeepSeek-V3', 'DeepSeek-V3', family='deepseek-v3')
m('deepseek-r1-zero', L, 'DeepSeek R1-Zero', 'deepseek-r', 'DeepSeek-R1-Zero', None, family='deepseek-r1')
m('deepseek-r1', L, 'DeepSeek R1', 'deepseek-r', 'DeepSeek-R1', 'DeepSeek-R1', family='deepseek-r1')
m('deepseek-r1-distill-qwen-32b', L, 'DeepSeek R1 Distill Qwen 32B', 'deepseek-distill', 'DeepSeek-R1-Distill-Qwen-32B', 'DeepSeek-R1-Distill-Qwen-32B', family='deepseek-r1')
m('deepseek-r1-distill-llama-70b', L, 'DeepSeek R1 Distill Llama 70B', 'deepseek-distill', 'DeepSeek-R1-Distill-Llama-70B', None, family='deepseek-r1')
m('deepseek-v3-1', L, 'DeepSeek V3.1', 'deepseek', 'DeepSeek-V3.1', 'DeepSeek-V3.1', family='deepseek-v3')
m('deepseek-v3-2-exp', L, 'DeepSeek V3.2-Exp', 'deepseek', 'DeepSeek-V3.2-Exp', 'DeepSeek-V3.2-Exp', family='deepseek-v3')
m('deepseek-v3-2', L, 'DeepSeek V3.2', 'deepseek', None, 'DeepSeek-V3.2', family='deepseek-v3')
m('deepseek-v4', L, 'DeepSeek V4 Pro', 'deepseek', 'DeepSeek-V4-Pro', 'DeepSeek-V4-Pro', family='deepseek-v4')
m('deepseek-v4-flash', L, 'DeepSeek V4 Flash', 'deepseek-flash', 'DeepSeek-V4-Flash', 'DeepSeek-V4-Flash', family='deepseek-v4')
m('deepseek-v4-1-flash', L, 'DeepSeek V4.1 Flash', 'deepseek-flash', 'DeepSeek V4.1 Flash', 'DeepSeek V4.1 Flash', family='deepseek-v4')

# ── Mistral ────────────────────────────────────────────────────────────────
L = 'mistral'
m('mistral-7b', L, 'Mistral 7B', 'mistral-small', 'Mistral 7B', 'Mistral 7B v0.1')
m('mixtral-8x7b', L, 'Mixtral 8x7B', 'mixtral', 'Mixtral 8x7B', 'Mixtral 8x7B', family='mixtral')
m('mistral-medium', L, 'Mistral Medium', 'mistral-medium', 'Mistral Medium')
m('mistral-large', L, 'Mistral Large', 'mistral-large', 'Mistral Large', 'Mistral Large', family='mistral-large')
m('mixtral-8x22b', L, 'Mixtral 8x22B', 'mixtral', 'Mixtral 8x22B', 'Mixtral 8x22B', family='mixtral')
m('mistral-nemo', L, 'Mistral NeMo', 'mistral-small', 'Mistral NeMo', 'Mistral NeMo')
m('mistral-large-2', L, 'Mistral Large 2', 'mistral-large', 'Mistral Large 2', 'Mistral Large 2 (Jul 2024)', family='mistral-large')
m('mistral-small-3', L, 'Mistral Small 3', 'mistral-small', 'Mistral Small 3', 'Mistral Small 3', family='mistral-small-3')
m('mistral-medium-3', L, 'Mistral Medium 3', 'mistral-medium', 'Mistral Medium 3', 'Mistral Medium 3', family='mistral-medium-3')
m('magistral-medium', L, 'Magistral Medium', 'magistral', 'Magistral Medium 1.1', None, family='magistral')
m('magistral-small', L, 'Magistral Small', 'magistral', 'Magistral Small 1.0', 'Magistral Small 1.0', family='magistral')
m('mistral-large-3', L, 'Mistral Large 3', 'mistral-large', 'Mistral Large 3', None, family='mistral-large')
m('mistral-small-3-1', L, 'Mistral Small 3.1', 'mistral-small', 'Mistral Small 3.1', 'Mistral Small 3.1', family='mistral-small-3')
m('mistral-small-4', L, 'Mistral Small 4', 'mistral-small', 'Mistral Small 4', None)
m('mistral-medium-3-5', L, 'Mistral Medium 3.5', 'mistral-medium', 'Mistral Medium 3.5', 'Mistral Medium 3.5', family='mistral-medium-3')

# ── xAI ────────────────────────────────────────────────────────────────────
L = 'xai'
m('grok-1', L, 'Grok-1', 'grok', 'Grok-1', None, family='grok-1')
m('grok-1-5', L, 'Grok-1.5', 'grok', 'Grok-1.5', None, family='grok-1')
m('grok-2', L, 'Grok-2', 'grok', 'Grok-2', 'Grok-2 (Dec 2024)', family='grok-2')
m('grok-3', L, 'Grok 3', 'grok', 'Grok 3', 'Grok 3', family='grok-3')
m('grok-3-mini', L, 'Grok 3 mini', 'grok-mini', 'Grok-3 mini', 'Grok-3 mini', family='grok-3')
m('grok-4', L, 'Grok 4', 'grok', 'Grok 4', 'Grok 4', family='grok-4')
m('grok-4-fast', L, 'Grok 4 Fast', 'grok-mini', 'Grok 4 Fast', 'Grok 4 Fast', family='grok-4')
m('grok-4-1', L, 'Grok 4.1', 'grok', 'Grok 4.1', None, family='grok-4')
m('grok-4-20', L, 'Grok 4.20', 'grok', 'Grok 4.20', 'Grok 4.20', family='grok-4')
m('grok-4-5', L, 'Grok 4.5', 'grok', 'Grok 4.5', 'Grok 4.5', family='grok-4')
m('grok-4-6', L, 'Grok 4.6', 'grok', 'Grok 4.6', 'Grok 4.6', family='grok-4')
m('grok-4-7', L, 'Grok 4.7', 'grok', 'Grok 4.7', None, family='grok-4')

# ── Alibaba / Qwen ─────────────────────────────────────────────────────────
L = 'alibaba'
m('qwen', L, 'Qwen', 'qwen', 'Qwen-14B', 'Qwen-14B', family='qwen-1')
m('qwen1-5', L, 'Qwen1.5', 'qwen', 'Qwen1.5-72B', None, family='qwen-1-5')
m('qwen2', L, 'Qwen2', 'qwen', 'Qwen2-72B', 'Qwen2-72B', family='qwen-2')
m('qwen2-5-72b', L, 'Qwen2.5 72B', 'qwen', 'Qwen2.5-72B', 'Qwen2.5-72B', family='qwen-2-5')
m('qwen2-5-32b', L, 'Qwen2.5 32B', 'qwen-mid', 'Qwen2.5-32B', 'Qwen2.5-32B', family='qwen-2-5')
m('qwen2-5-coder-32b', L, 'Qwen2.5-Coder 32B', 'qwen-coder', 'Qwen2.5-Coder (32B)', 'Qwen2.5-Coder-32B', family='qwen-2-5')
m('qwen2-5-max', L, 'Qwen2.5-Max', 'qwen-max', 'Qwen2.5-Max', 'Qwen2.5-Max', family='qwen-2-5')
m('qwq-32b', L, 'QwQ-32B', 'qwen-mid', 'QwQ-32B', 'QwQ-32B', family='qwen-2-5')
m('qwen3-235b-a22b', L, 'Qwen3 235B-A22B', 'qwen', 'Qwen3-235B-A22B', 'Qwen3-235B-A22B', family='qwen-3')
m('qwen3-coder', L, 'Qwen3-Coder 480B-A35B', 'qwen-coder', 'Qwen3-Coder-480B-A35B', None, family='qwen-3')
m('qwen3-max', L, 'Qwen3-Max', 'qwen-max', 'Qwen3-Max', 'Qwen3-Max', family='qwen-3')
m('qwen3-5', L, 'Qwen3.5 397B-A17B', 'qwen', 'Qwen3.5 397B-A17B', 'Qwen3.5 397B-A17B', family='qwen-3-5')
m('qwen3-6-plus', L, 'Qwen3.6-Plus', 'qwen-plus', 'Qwen 3.6 Plus', 'Qwen 3.6 Plus', family='qwen-3-6')
m('qwen3-7-max', L, 'Qwen3.7-Max', 'qwen-max', 'Qwen3.7-Max', 'Qwen3.7-Max', family='qwen-3-7')
m('qwen3-8-max', L, 'Qwen3.8-Max', 'qwen-max', 'Qwen 3.8 Max', 'Qwen 3.8 Max', family='qwen-3-8')
m('qwen3-8-2-4t', L, 'Qwen3.8 2.4T-A95B', 'qwen', 'Qwen3.8-2.4T-A95B', None, family='qwen-3-8')

# ── Moonshot ───────────────────────────────────────────────────────────────
L = 'moonshot'
m('kimi-k1-5', L, 'Kimi k1.5', 'kimi', 'Kimi k1.5', None)
m('kimi-k2', L, 'Kimi K2', 'kimi', 'Kimi K2', 'Kimi K2 (Jul 2025)', family='kimi-k2')
m('kimi-k2-thinking', L, 'Kimi K2 Thinking', 'kimi', 'Kimi K2 Thinking', 'Kimi K2 Thinking', family='kimi-k2')
m('kimi-k2-5', L, 'Kimi K2.5', 'kimi', 'Kimi K2.5', 'Kimi K2.5', family='kimi-k2')
m('kimi-k2-6', L, 'Kimi K2.6', 'kimi', 'Kimi K2.6', 'Kimi K2.6', family='kimi-k2')
m('kimi-k3', L, 'Kimi K3', 'kimi', 'Kimi K3', 'Kimi K3', family='kimi-k3')

# ── Zhipu / Z.ai ───────────────────────────────────────────────────────────
L = 'zhipu'
m('glm-130b', L, 'GLM-130B', 'glm', 'GLM-130B', None, org='Tsinghua University')
m('glm-4', L, 'GLM-4', 'glm', 'GLM-4 (0116)', None, family='glm-4')
m('glm-4-plus', L, 'GLM-4-Plus', 'glm', 'GLM-4-Plus', None, family='glm-4')
m('glm-4-5', L, 'GLM-4.5', 'glm', 'GLM-4.5', None, family='glm-4-5')
m('glm-4-6', L, 'GLM-4.6', 'glm', 'GLM-4.6', None, family='glm-4-5')
m('glm-4-7', L, 'GLM-4.7', 'glm', 'GLM-4.7', 'GLM-4.7', family='glm-4-5')
m('glm-5', L, 'GLM-5', 'glm', 'GLM-5', 'GLM-5', family='glm-5')
m('glm-5-1', L, 'GLM-5.1', 'glm', 'GLM-5.1', 'GLM-5.1', family='glm-5')
m('glm-5-2', L, 'GLM-5.2', 'glm', 'GLM-5.2', 'GLM-5.2', family='glm-5')
m('glm-5-3', L, 'GLM-5.3', 'glm', 'GLM-5.3', 'GLM-5.3', family='glm-5')

# ── MiniMax ────────────────────────────────────────────────────────────────
L = 'minimax'
m('minimax-abab6-5', L, 'abab6.5', 'minimax', 'abab6.5', None)
m('minimax-text-01', L, 'MiniMax-Text-01', 'minimax', 'MiniMax-Text-01', None, family='minimax-01')
m('minimax-m1', L, 'MiniMax-M1', 'minimax', 'MiniMax-M1-80k', None, family='minimax-m1')
m('minimax-m2', L, 'MiniMax-M2', 'minimax', 'MiniMax-M2', None, family='minimax-m2')
m('minimax-m2-1', L, 'MiniMax-M2.1', 'minimax', 'MiniMax-M2.1', None, family='minimax-m2')
m('minimax-m2-5', L, 'MiniMax-M2.5', 'minimax', 'MiniMax-M2.5', 'MiniMax-M2.5', family='minimax-m2')
m('minimax-m2-7', L, 'MiniMax-M2.7', 'minimax', 'MiniMax-M2.7', 'MiniMax-M2.7', family='minimax-m2')
m('minimax-m3', L, 'MiniMax-M3', 'minimax', 'MiniMax-M3', 'MiniMax-M3', family='minimax-m3')

# ── Other ──────────────────────────────────────────────────────────────────
L = 'other'
m('gpt-j', L, 'GPT-J', 'eleutherai', 'GPT-J-6B', org='EleutherAI')
m('megatron-turing-nlg', L, 'Megatron-Turing NLG 530B', 'nvidia', 'Megatron-Turing NLG 530B', org='Microsoft, Nvidia')
m('jurassic-1', L, 'Jurassic-1 Jumbo', 'ai21', 'Jurassic-1-Jumbo', org='AI21 Labs')
m('gpt-neox-20b', L, 'GPT-NeoX-20B', 'eleutherai', 'GPT-NeoX-20B', org='EleutherAI')
m('bloom', L, 'BLOOM', 'bigscience', 'BLOOM-176B', org='BigScience')
m('falcon-180b', L, 'Falcon 180B', 'tii', 'Falcon-180B', 'Falcon-180B', org='Technology Innovation Institute')
m('yi-34b', L, 'Yi-34B', 'yi', 'Yi-34B', 'Yi-34B', org='01.AI')
m('command-r-plus', L, 'Command R+', 'cohere', 'Command R+', 'Command R+', org='Cohere')
m('nemotron-4-340b', L, 'Nemotron-4 340B', 'nvidia', 'Nemotron-4 340B', None, org='Nvidia')
m('llama-3-1-nemotron-70b', L, 'Llama 3.1 Nemotron 70B', 'nvidia', 'Llama-3.1-Nemotron-70B-Instruct', None, org='Nvidia')
m('amazon-nova-pro', L, 'Amazon Nova Pro', 'amazon', 'Amazon Nova Pro', 'Amazon Nova Pro', org='Amazon')
m('phi-4', L, 'Phi-4', 'microsoft', 'Phi-4', 'Phi-4', org='Microsoft')
m('olmo-2', L, 'OLMo 2 32B', 'ai2', 'OLMo 2 32B', None, org='Allen Institute for AI')
m('nemotron-3-ultra', L, 'Nemotron 3 Ultra', 'nvidia', 'Nemotron 3 Ultra', 'Nemotron 3 Ultra', org='Nvidia')
m('inkling', L, 'Inkling', 'thinking-machines', 'Inkling', 'Inkling', org='Thinking Machines')
