#!/usr/bin/env node
// Merges data/**/*.yaml into site/data.json and site/data.js.
//
// Both outputs are committed. The site never parses YAML: data.json is fetched
// over http, and data.js (`window.TIMELINE_DATA = ...`) is a <script> fallback so
// the page also works when opened directly from disk, where fetch() hits CORS.
//
// Output key order is deterministic so regenerating produces byte-identical files
// and diffs stay reviewable.

import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { loadDataset, EVENT_TYPES, EDGE_TYPES } from './validate.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = join(ROOT, 'site');

const EVENT_KEYS = ['type', 'date', 'precision', 'confidence', 'basis', 'bounds', 'source'];
const MODEL_KEYS = [
  'id', 'lab', 'org', 'name', 'family', 'product_line', 'api_name', 'tags', 'modalities',
  'context_window', 'params', 'open_weights', 'licence', 'hf_id', 'epoch_id', 'notes', 'events',
];
const EDGE_KEYS = ['from', 'to', 'type', 'confidence', 'basis', 'source'];
const SCORE_KEYS = ['model', 'eci', 'ci_low', 'ci_high', 'note'];
const LIFECYCLE_RANK = Object.fromEntries(EVENT_TYPES.map((t, i) => [t, i]));

/** Rebuild an object with keys in a fixed order, dropping empty values. */
function ordered(obj, keys) {
  const out = {};
  for (const k of keys) {
    const v = obj[k];
    if (v === undefined || v === null) continue;
    if (typeof v === 'string' && v.trim() === '') continue;
    if (Array.isArray(v) && v.length === 0) continue;
    out[k] = typeof v === 'string' ? v.trim() : v;
  }
  return out;
}

function normaliseEvent(ev) {
  const out = ordered(ev, EVENT_KEYS);
  if (out.bounds) {
    const b = {};
    if (ev.bounds.earliest) b.earliest = ev.bounds.earliest;
    if (ev.bounds.latest) b.latest = ev.bounds.latest;
    if (Object.keys(b).length) out.bounds = b; else delete out.bounds;
  }
  return out;
}

function normaliseModel(model, labId) {
  const events = (model.events || [])
    .map(normaliseEvent)
    .sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : LIFECYCLE_RANK[a.type] - LIFECYCLE_RANK[b.type]));
  return ordered({ ...model, lab: labId, events }, MODEL_KEYS);
}

function build() {
  const { labs, modelFiles, lineage, scores } = loadDataset();

  const models = [];
  for (const { doc } of modelFiles) {
    for (const m of doc.models || []) models.push(normaliseModel(m, doc.lab));
  }

  // Sort by lab order, then by each model's earliest LIFECYCLE event. training_cutoff
  // is excluded: it describes the training data, not the model's place in time, and
  // sorting on it groups unrelated models that happen to share a cutoff.
  const labOrder = Object.fromEntries(labs.map((l) => [l.id, l.order ?? 999]));
  const firstDate = (m) => {
    const ev = m.events.find((e) => e.type !== 'training_cutoff');
    return ev ? ev.date : (m.events[0]?.date ?? '9999-12-31');
  };
  models.sort((a, b) => (labOrder[a.lab] - labOrder[b.lab]) || firstDate(a).localeCompare(firstDate(b)) || a.id.localeCompare(b.id));

  const edges = (lineage?.edges || [])
    .map((e) => ordered(e, EDGE_KEYS))
    .sort((a, b) => a.from.localeCompare(b.from) || a.to.localeCompare(b.to) || a.type.localeCompare(b.type));

  const eci = {
    source: scores?.source ?? null,
    retrieved: scores?.retrieved ?? null,
    values: (scores?.scores || [])
      .map((s) => ordered(s, SCORE_KEYS))
      .sort((a, b) => a.model.localeCompare(b.model)),
  };

  const dated = models.flatMap((m) => m.events.map((e) => e.date));
  const payload = {
    // `generated` is deliberately omitted: a timestamp would make every rebuild
    // a diff, defeating the byte-identical check.
    schema_version: 2,
    event_types: EVENT_TYPES,
    edge_types: EDGE_TYPES,
    domain: { start: dated.reduce((a, b) => (a < b ? a : b)), end: dated.reduce((a, b) => (a > b ? a : b)) },
    labs: labs
      .slice()
      .sort((a, b) => (a.order ?? 999) - (b.order ?? 999))
      .map((l) => ordered(l, ['id', 'name', 'color', 'order', 'country', 'homepage'])),
    models,
    lineage: edges,
    scores: { eci },
  };

  const json = JSON.stringify(payload, null, 2) + '\n';
  writeFileSync(join(SITE, 'data.json'), json);
  writeFileSync(
    join(SITE, 'data.js'),
    '// Generated by scripts/build-data.mjs — do not edit.\n' +
      '// Loaded as a <script> fallback so the page works from file:// where fetch() is blocked.\n' +
      'window.TIMELINE_DATA = ' + json.trimEnd() + ';\n'
  );

  console.log(`✓ wrote site/data.json + site/data.js — ${models.length} models, ${payload.labs.length} labs, ` +
    `${edges.length} edges, ${eci.values.length} ECI scores`);
  console.log(`  domain ${payload.domain.start} → ${payload.domain.end}`);
}

build();
